# -*- coding: utf-8 -*-
"""
Created on Thu Sep 29 15:23:59 2016

@author: isidoro
"""

class ConfParameters:
    
    def __init__ (self, dictionary):
        self.cabecera_ranking_individual = dictionary.pop("cabecera_ranking_individual")
        self.cabecera_ranking_clubes = dictionary.pop("cabecera_ranking_clubes")
        self.cabecera_grupos_cerrados = dictionary.pop("cabecera_grupos_cerrados")
        self.carreras = dictionary.pop("carreras")
        self.divisiones = dictionary.pop("divisiones")
        self.division_honor = dictionary.pop("division_honor")
        self.tipos_organizador = dictionary.pop("tipos_organizador")
        self.licencias = dictionary.pop("licencias")
        self.tipos_categoria_ranking_clubes = dictionary.pop("tipos_categoria_ranking_clubes")
        self.fecha_actual = dictionary.pop("fecha_actual")
        self.temporada_actual = dictionary.pop("temporada_actual")
        self.puntos_penalizacion = dictionary.pop("puntos_penalización")
        self.puntos_ganador_nac = dictionary.pop("puntos_ganador_nac")
        self.puntos_ganador_inter = dictionary.pop("puntos_ganador_inter")
        self.puntos_ganador_inter_aux = dictionary.pop("puntos_ganador_inter_aux")
        self.puntos_fuera_categoria = dictionary.pop("puntos_fuera_categoria")
        self.num_carreras_total = dictionary.pop("num_carreras_total")
        self.num_carreras_total_elite = dictionary.pop("num_carreras_total_elite")
        self.num_carreras_media = dictionary.pop("num_carreras_media")
        self.num_carreras_media_elite = dictionary.pop("num_carreras_media_elite")
        self.num_carreras_organizador = dictionary.pop("num_carreras_organizador")
        self.coeficiente_clubes = dictionary.pop("coeficiente_clubes")
        self.num_trofeos = dictionary.pop("num_trofeos")
        self.minimo_elite = dictionary.pop("minimo_elite")
        self.minimo_21A = dictionary.pop("minimo_21A")
        self.minimo_21Aaux = dictionary.pop("minimo_21Aaux")
        self.minimo_21B = dictionary.pop("minimo_21B")
        self.minimo_20 = dictionary.pop("minimo_20")
        self.minimo_20aux = dictionary.pop("minimo_20aux")
        self.coef_elite = dictionary.pop("coef_elite")
        self.coef_20a = dictionary.pop("coef_20a")
        self.coef_35a = dictionary.pop("coef_35a")
        self.coef_18a = dictionary.pop("coef_18a")
        self.coef_21a = dictionary.pop("coef_21a")
        self.coef_40 = dictionary.pop("coef_40")
        self.coef_16 = dictionary.pop("coef_16")
        self.coef_45 = dictionary.pop("coef_45")
        self.coef_50 = dictionary.pop("coef_50")
        self.coef_12 = dictionary.pop("coef_12")
        self.coef_14 = dictionary.pop("coef_14")
        self.coef_21b = dictionary.pop("coef_21b")
        self.coef_55 = dictionary.pop("coef_55")
        self.coef_60 = dictionary.pop("coef_60")
        self.coef_65 = dictionary.pop("coef_65")
        self.coef_70 = dictionary.pop("coef_70")
        self.coef_1820b = dictionary.pop("coef_1820b")
        self.coef_35b = dictionary.pop("coef_35b")
        self.num_max_corredores = dictionary.pop("num_max_corredores")
        self.opcion_calculo_m1 = dictionary.pop("opcion_calculo_m1")
        self.opcion_ranking_individual = dictionary.pop("opcion_ranking_individual")
        #extra parameters in case of need
        self.parametro1 = dictionary.pop("parametro1")
        self.parametro2 = dictionary.pop("parametro2")
        self.parametro3 = dictionary.pop("parametro3")